# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JnnFac84OSIvvNG7_rWIMo8FKrc37mlP
"""

print ("A")
print ("B")
print ("C")

"""Prediction: A and B
Actual Answer: A and C
"""

x = 10
y = x
x = 20
print (y)

"""Prediction: 10
Actual Answer: 10
"""

x = 5
x = x + 1
print (x)

"""Prediction: 6
Actual Answer: 6
"""

def add (a, b):
  print ("inside")
  return a + b

print ("before")
add (2, 3)
print ("after")

"""Prediction: before inside after
Actual Answer: before inside after
"""

def make ():
  x = [1, 2]
  return x

lst = make ()
print (lst)

"""Prediction: It print something
Actual Answer: It print something
"""

lst = [1, 2]
lst.append (3)
print (lst)

lst = [1, 2]
lst = [9, 10]
print (lst)

"""Prediction: First: 1, 2, 3. Second: 9, 10
Actual Answer: First: 1, 2, 3. Second: 9, 10
"""

from re import A
def f(x):
      x = x + 1

a = 10
f (a)
print (a)

"""Prediction: 10
Actual Answer: 10
"""

for i in [1, 2, 3]:
  print (i)

"""Prediction: 1
Actual Answer: 3
"""

it = iter ([1, 2])
print (next(it))
print (next(it))
print (next(it))

"""Prediction: Error
Actual Answer: Error
"""

def demo ():
  print ("A")
  yield 1
  print ("B")

x = demo ()

"""Prediction: No
Actual Answer: No
"""

g = demo ()
print (next(g))
print (next(g))

"""Prediction: A then B
Actual Answer: Error
"""

def outer ():
  x = 10
  def inner ():
    return x
  return inner

f = outer ()
print (f())

"""Prediction: Crashes
Actual Answer: Prints a number
"""

def deco (fn):
  def wrapper ():
    print ("before")
    fn ()
    print ("after")
  return wrapper

@deco
def hello ():
  print ("hello")

hello ()

"""Prediction: 3
Actual Answer: 3
"""

class A:
  x = 10

a = A ()
print (a.x)

"""Prediction: Error
Actual Answer: Prints a number
"""

class MyRange:
  def _ _iter_ _(self):
  return self

  def _ _next_ _(self):
    raise StopIteration

for x in MyRange ():
  print (x)

"""Prediction: Runs
Actual Answer: Crashes
"""